### PR TITLE
Resolve #180 #160 Improve tool feedback

### LINKED ISSUE #160: NodeCreationTool for ActivityNodes behaves unexpected
It's (somehow) possible to create Nodes inside of already existing ActivityNodes which resizes the containing node.
This operation should not allowed in the first place which should probably checked on both client and server side (using EditConfigs/TypeHints).
container_bug

### LINKED ISSUE #180: Tool feedback is temporarily gone during usage
When using tools (create node tool, resize tool), the visual feedback is temporarily gone. 

This is very visible when you use the resize tool with the resize handles. The handles are shown, then temporarily gone and then reappear again. But you can also reproduce this by using the create node tool in 'stamp' mode (keeping the Ctrl key pressed): The '+' on the mouse cursor is temporarily back to normal.

My guess is that it is because the feedback uses a command structure so while the server update is happening through one command, the feedback is not visible before the feedback is reapplied again or something similar.

### PR DESCRIPTION
**Pull request by tortmayr**
Summary:
- Introduce genericApplyCursorCSSFeedbackCommand
-Introduce FeedbackAwareUpdateModelCommand which replaces the previous error-prone approach to observe server updates (this resolves #180)
- Implement editConfig application as Feedback command
- Context-aware allowed/not allowed Feeback for Tools based on the mouseOver event (this resolves #160)
- EdgeCreationTools can now be cancelled with right-click
- Various/Minor fixes to ensure that the different default tools are cleaned up properly an do not interfere with each other

improveFeedback

### CODE REVIEW

File: client/packages/glsp-sprotty/src/features/hints/type-hints-action-initializer.ts [hunk 1]
```diff
@@ -13,51 +13,75 @@
...
+    readonly priority = 10;
+    constructor(@inject(TYPES.Action) protected action: ApplyEditConfigAction) {
+        super();
+    }
+    execute(context: CommandExecutionContext): CommandResult {
+        context.root.index.all().forEach(element => {
+            const config = this.action.editConfigs.get(element.type)
+            if (config) {
+                Object.assign(element, config);
+
```
Comment (martin-fleck-at) [inline client/packages/glsp-sprotty/src/features/hints/type-hints-action-initializer.ts]: Nit: empty line

File: client/packages/glsp-sprotty/src/utils/smodel-util.ts [hunk 2]
```diff
@@ -42,7 +51,7 @@ export function isSelected(element: SModelElement): element is SModelElement & S
 }
 
 export function isSelectedBoundsAware(element: SModelElement): element is SModelElement & BoundsAware & Selectable {
-    return isBoundsAware(element) && isSelected(element);
+    return isBoundsAware(element) && isSelected(element) && !isRoutable(element);
```
Comment (martin-fleck-at) [inline client/packages/glsp-sprotty/src/utils/smodel-util.ts]: I am not sure why whether it is a good idea to simply add this here since the function name does not reflect this. There only seems to be a single place where this is currently used (change-bounds-tool) so we could simply have added the condition there as well or renamed the function here.

Comment (tortmayr) [reply client/packages/glsp-sprotty/src/utils/smodel-util.ts]: Good point. For now, it should suffice to add the condition to the change-bounds-tool

**Comment by tortmayr** [comment]
I fixed the unintended behaviour when selecting forbidden targets.
In doing so I noticed the the sprotty selection tool also sends `SwitchEditModeActions` which leeds to some issues. (Clicking on an edge with a creation tool creates routing handles, clicking on the empty graph during edge creation/reconnection creates routing handles on the feedback edge etc.)
I bypassed this problem by subclassing `SwitchEditModeAction/SwitchEditModeCommand` for our purposes and binding the "normal" SwitchEditModeAction to an empty handler
