### PR TITLE
Fix #311 Implement GLSPConfigurator for websocket connections

### LINKED ISSUE #311: P2 counterpart of glsp-server-websocket not working correctly

### PR DESCRIPTION
**Pull request by tortmayr**
The P2 counterpart of glsp-server-websocke was not working because javax.websocket relies on some services that should be provided via `ServiceLoader`. This is not always the case when using the plugin in an OSGI context.

This change introduces a `GLSPConfigurator` for ServerEndpoints that has a fallback option if no service is provided via ServiceLoader.

(Integrated and tested locally in the glsp-p2 repository)

### CODE REVIEW

File: server/glsp-server-websocket/src/main/java/com/eclipsesource/glsp/server/websocket/GLSPConfigurator.java [hunk 1]
```diff
@@ -0,0 +1,71 @@
...
+	private Configurator containerConfigurator;
+	private Injector injector;
+
+	public GLSPConfigurator(Injector injector) {
+		this.injector = injector;
+	}
+
+	Configurator getContainerConfigurator() {
+		if (containerConfigurator == null) {
+			containerConfigurator = ServiceLoader.load(javax.websocket.server.ServerEndpointConfig.Configurator.class)
```
Comment (planger) [inline server/glsp-server-websocket/src/main/java/com/eclipsesource/glsp/server/websocket/GLSPConfigurator.java]: Afais, you don't need to mention the entire qualified name of the class ServerEndpointConfig.Configurator.
