### PR TITLE
Resolve #201: Provide selection service and use in tools

### LINKED ISSUE #201: Implement SelectionService to track selected elements reliably
Currently there is no easy way to determine the selected elements. In most cases, we use one of the following two approaches, depending on where we need this information. However, both approaches do not work in all cases:

- Iterate through the complete model and collect all elements that have the `selected` flag. This flag is currently set by the `SelectAction` and its corresponding command. 
Therefore, this approach can only be used when we can ensure that all commands that work on the selected flag have been processed as otherwise we may work on outdated information.

- Listening to selection changes based on mouse events and aggregating the information  (`SelectionTracker` class). This uses the `MoveMouseListener` from Sprotty which actually dispatches the `SelectAction` in order to get the selection information as soon as possible. This is necessary for most tools which need to act on the mouse-listener level themselves.
The main issue for using a mouse listener is that any other listeners/actions/commands that dispatch a `SelectAction` or the `DiagramKeybindingContribution` that selects all elements (ctrl+a) cannot be tracked. Furthermore, the tool listeners inherit from the `SelectionTracker` class but tools can be enabled and disabled at any time, so any selection that is present prior to the tools activation is lost as well.

What we need is a reliable way to track selection and make that information available as soon as possible. The selection service should track any action that manipulates the `selected` flag but also react to what information is sent from the server (if we allow the server to manipulate selection). Ideally, this information is available to the tools and the tools can react to selection changes accordingly.

### PR DESCRIPTION
**Pull request by martin-fleck-at**
### Selection Service
- Provide selection service that tracks selected elements in model root
- Provide custom SelectCommand / SelectAllCommand that update service
- Provide Select*FeedbackCommands that update model (sent by service)

### Mouse Tool
- Provide mouse tool that executes listeners in order of rank
- Execute selection mouse listener before other listeners
- Other listeners are run after so they can rely on selection service

### Root Change Listener
- Provide listener mechanism for root changes to properly update service

### Tools
- Ensure change bounds tool properly reacts to selection changes
- Ensure edge edit tool properly reacts to selection changes

### CODE REVIEW

File: client/packages/glsp-sprotty/src/base/model/update-model-command.ts [hunk 1]
```diff
@@ -30,6 +30,11 @@ import { IFeedbackActionDispatcher } from "src/features/tool-feedback/feedback-a
 import { FeedbackCommand } from "../../features/tool-feedback/model";
 import { GLSP_TYPES } from "../../types";
 
+@injectable()
+export class SModelRootListener {
```
Comment (tortmayr) [inline client/packages/glsp-sprotty/src/base/model/update-model-command.ts]: Shouldn't `SmodelRootListener` be declared as interface?

File: client/packages/glsp-sprotty/src/features/select/selection-service.ts [hunk 2]
```diff
@@ -0,0 +1,112 @@
...
+import { inject, injectable, multiInject, optional } from "inversify";
+import { Action, ILogger, SModelRoot, TYPES } from "sprotty";
+
+import { SModelRootListener } from "../../base/model/update-model-command";
+import { GLSP_TYPES } from "../../types";
+import { IFeedbackActionDispatcher } from "../tool-feedback/feedback-action-dispatcher";
+import { SelectFeedbackAction } from "./action-definitions";
+
+@injectable()
+export class SelectionListener {
```
Comment (tortmayr) [inline client/packages/glsp-sprotty/src/features/select/selection-service.ts]: Same as above. Interface vs. class

File: client/packages/glsp-sprotty/src/features/select/selection-service.ts [hunk 3]
```diff
@@ -0,0 +1,112 @@
...
+    @inject(TYPES.ILogger) protected logger: ILogger;
+
+    constructor(@multiInject(GLSP_TYPES.SelectionListener) @optional() protected selectionListeners: SelectionListener[] = []) { }
+
+    register(selectionListener: SelectionListener) {
+        this.selectionListeners.push(selectionListener);
+    }
+
+    deregister(selectionListener: SelectionListener) {
+        const index = this.selectionListeners.indexOf(selectionListener);
```
Comment (tortmayr) [inline client/packages/glsp-sprotty/src/features/select/selection-service.ts]: You could reuse the remove method from`utils/array-utils.ts`here
