### PR TITLE
Resolve #326 - Improve exception handling and client notification

### LINKED ISSUE #326: Improve exception handling and client notification
Catch exceptions from GLSP Handlers, wrap them in ServerStatusAction and send action to client

### PR DESCRIPTION
**Pull request by tortmayr**

### CODE REVIEW

File: server/glsp-api/src/main/java/com/eclipsesource/glsp/api/action/kind/ServerStatusAction.java [hunk 1]
```diff
@@ -21,6 +21,7 @@
 public class ServerStatusAction extends Action {
 	private String severity;
 	private String message;
+	private String details;
 
 	public ServerStatusAction() {
```
Comment (martin-fleck-at) [inline server/glsp-api/src/main/java/com/eclipsesource/glsp/api/action/kind/ServerStatusAction.java]: Please restore the `hashCode` and `equals` method of this class with the new field ;-)

File: server/glsp-api/src/main/java/com/eclipsesource/glsp/api/utils/ServerStatusUtil.java [hunk 2]
```diff
@@ -0,0 +1,61 @@
...
+	public static ServerStatusAction warn(String message) {
+		return new ServerStatusAction(new ServerStatus(Severity.WARNING, message));
+	}
+
+	public static ServerStatusAction error(String message, String details) {
+		return new ServerStatusAction(new ServerStatus(Severity.ERROR, message, details));
+	}
+
+	public static ServerStatusAction error(Exception e) {
+		return error(e.getMessage(), printStacktrace(e.getCause()));
```
Comment (martin-fleck-at) [inline server/glsp-api/src/main/java/com/eclipsesource/glsp/api/utils/ServerStatusUtil.java]: If there is no message then the client will show `undefined`, cf. screenshot below. Maybe we could show the class name if there is no message so that we know at least what type of exception it is, e.g., this happened with a NPE:

Selection_087

File: client/packages/theia-integration/src/browser/diagram/glsp-theia-sprotty-connector.ts [hunk 3]
```diff
@@ -60,8 +63,18 @@ export class GLSPTheiaSprottyConnector implements TheiaSprottyConnector, GLSPThe
 
     showStatus(widgetId: string, status: ServerStatusAction): void {
         const widget = this.widgetManager.getWidgets(this.diagramManager.id).find(w => w.id === widgetId);
+
         if (widget instanceof DiagramWidget)
             widget.setStatus(status);
+
+        if (status.severity === "ERROR") {
+            const details = isGLSPServerStatusAction(status) ? status.details : "";
+            this.messageService.error(status.message, "Show details").then(result => {
```
Comment (martin-fleck-at) [inline client/packages/theia-integration/src/browser/diagram/glsp-theia-sprotty-connector.ts]: Not sure if this is possible but sometimes the error does not provide any details. In that case maybe the popup should not show the 'Show details' at all as we end up with an empty message box:

Selection_087
Selection_088
