### PR TITLE
Fix #105 "stamp" mode not working

### LINKED ISSUE #105: "Stamp Mode" for tools not working correctly
There seems to be a problem with the "stamp mode"  when using two tools consecutively.

The issue occurs if I create a couple of task nodes in stamp mode (i.e. holding <i>ctrl</i>) then switch to the merge node tool and use the stamp mode again.  For each tool execution a merge node and a task node will be  created. Seems like the previous active tool is not properly cleaned up.

image

### PR DESCRIPTION
**Pull request by tortmayr**
Modifies the <i>StandardToolsEnablingKeyListener</i> to ensure that the StandardTools get enabled after a CreationTool has been used in "stamp-mode" (i.e. while holding ctrl)

In addition, this contains a minor refactoring for the <i>ExtendedKeyTool</i> which was using (and exporting) an unsafe custom type guard function instead of a simple 'instanceof' check

### CODE REVIEW

File: client/packages/glsp-sprotty/src/features/tool-manager/tool-manager.ts [hunk 1]
```diff
@@ -152,11 +153,18 @@ export class ToolManagerActionHandlerInitializer implements IActionHandlerInitia
...
+export class StandardToolsEnablingKeyListener extends ExtendedKeyListener {
     keyDown(element: SModelElement, event: KeyboardEvent): Action[] {
         if (matchesKeystroke(event, 'Escape')) {
             return [new EnableStandardToolsAction()];
         }
         return [];
     }
+
+    keyUp(element: SModelElement, event: KeyboardEvent): Action[] {
+        if (matchesKeystroke(event, 'ControlLeft' || 'ControlRight')) {
```
Comment (planger) [inline client/packages/glsp-sprotty/src/features/tool-manager/tool-manager.ts]: I think I'm not really in favor of this fix for the following reasons:

- The StandardToolsEnablingKeyListener is a very general thing -- ie enabling hitting escape to exit any special mode whatsoever. By adding this Control key handling, it becomes something that handles a very specific issue in the stamp mode.
- It seems that this may introduce very unforeseen side-effects. E.g. selecting a tool and hitting Ctrl will disable the tool. Hitting Ctrl once should usually not have any side-effects.
- It breaks the normal behavior of the stamp mode: Ctrl-down click Ctrl-up Ctrl-down click -- with this listener it only works if you keep holding down the Ctrl key.

**Comment by tortmayr** [comment]
The problem is that the creation tools only send an "EnableStanardToolsAction" if ctrl is not pressed.
https://github.com/eclipsesource/graphical-lsp/blob/b27c6838b51e4d0c99050b21230382ab41c377a3/client/packages/glsp-sprotty/src/features/tools/creation-tool.ts#L53-L55

Without the EnableStandardToolsAction the tool remains enabled when selecting another (creation) tool.

**Comment by planger** [comment]
Right, thanks for the feedback!

Wouldn't then be the best solution that we disable all currently enabled tools on `EnableToolsAction` rather than enabling those in addition? We could make that a parameter of the `EnableToolsAction` (whether or not to disable currently enabled tools). This way the palette could set this parameter in the action to ensure that whenever the user selects a tool in the palette, it not only enables the selected tool but also clears the current selection to avoid multiple "non-standard" tools being active at the same time?

**Comment by tortmayr** [comment]
I updated the change as discussed and we now  disable all currently enabled tools on EnableToolsAction
